### ISSUE TITLE
Nondeterministic bug with specific datashape on load

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1341]
The `string[25]` seems to be the culprit in the dshape below.

When I make it a `string` type, things work fine.

So something's going on with the `string[N]` dshape type.

```python
from __future__ import print_function
import blaze as bz

ds = bz.dshape("""var * {
                  k: date,
                  n: string[25],
                  }""")

d = bz.Data('./test.csv', dshape=ds)
print(bz.compute(d.nrows))
```

test.csv:

```
2015-03-13,FOO THE BAR
2014-01-29,BAZ THE QUUX
```

Sometimes, I get an `OSError` with a weird `Temp(URL(CSV))` object:

```python
$ python breakage.py
/Users/ksmith/work/odo/odo/core.py:65: FailedConversionWarning: Failed on CSV -> chunks(pandas.DataFrame). Working around
Error message:
the dtype <U25 is not supported for parsing
  warn(FailedConversionWarning(A, B, e))
Traceback (most recent call last):
  File "breakage.py", line 31, in <module>
    print(bz.compute(d.nrows))
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/ksmith/work/blaze/blaze-repo/blaze/interactive.py", line 171, in compute
    return compute(expr, resources, **kwargs)
[...]
RuntimeError: maximum recursion depth exceeded in cmp
```

Other times (nondeterministically), I get a different exception:

```python
❯❯❯ python breakage.py
/Users/ksmith/work/odo/odo/core.py:65: FailedConversionWarning: Failed on CSV -> chunks(pandas.DataFrame). Working around
Error message:
the dtype <U25 is not supported for parsing
  warn(FailedConversionWarning(A, B, e))
Traceback (most recent call last):
  File "breakage.py", line 11, in <module>
    print(bz.compute(d.nrows))
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/ksmith/work/blaze/blaze-repo/blaze/interactive.py", line 171, in compute
    return compute(expr, resources, **kwargs)
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/ksmith/work/blaze/blaze-repo/blaze/compute/core.py", line 454, in compute
    for e, dat in d2.items()
  File "/Users/ksmith/work/blaze/blaze-repo/blaze/compute/core.py", line 455, in <genexpr>
    if e in expr2
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/ksmith/work/blaze/blaze-repo/blaze/compute/csv.py", line 54, in pre_compute
    return into(pd.DataFrame, data, dshape=leaf.dshape, **kwargs)
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/ksmith/work/odo/odo/into.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "/Users/ksmith/work/odo/odo/into.py", line 50, in into_type
    return convert(a, b, dshape=dshape, **kwargs)
  File "/Users/ksmith/work/odo/odo/core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/Users/ksmith/work/odo/odo/core.py", line 68, in _transform
    **kwargs)
  File "/Users/ksmith/work/odo/odo/core.py", line 60, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)
  File "/Users/ksmith/work/odo/odo/backends/aws.py", line 213, in text_to_temp_s3_text
    return append(Temp(S3(subtype))(uri, **kwargs), data)
  File "/Users/ksmith/work/odo/odo/backends/aws.py", line 80, in __init__
    kwargs))
  File "/Users/ksmith/anaconda/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Anonymous access is forbidden for this operation</Message><RequestId>63D846B536C3E749</RequestId><HostId>/9jvIf2d9y8tixIHSVE9LkNDiqFFO9GCj8LFFeqeARo3t/0/hn/FlC/68mgoHdfJoT8DYdh7s4E=</HostId></Error>
Exception AttributeError: AttributeError("'Temp(S3(CSV))' object has no attribute 'object'",) in <bound method Temp(S3(CSV)).__del__ of <odo.temp.Temp(S3(CSV)) object at 0x11365ac10>> ignored
```

This one involves `Temp(S3(CSV))` for some strange reason.

The non-repeatability of this error is disturbing.

**Comment by cpcloud** [comment]
@kwmsmith thanks for tracking this down ... i'm debugging it now

**Comment by cpcloud** [comment]
ok i got to the bottom of this 

the most important thing to notice is this:

```
the dtype <U25 is not supported for parsing
  warn(FailedConversionWarning(A, B, e))
```

**Comment by cpcloud** [comment]
That will try the next shortest path in the graph. I'm not sure what happens if two paths are of equal length what choice is made. I'm also not sure if the two paths that seem to be happening non-deterministically are of equal length

**Comment by cpcloud** [comment]
This is really an odo issue, moving over there.
