### ISSUE TITLE
Reduction + Mongo NotImplementedError: Don't know how to compute

### ISSUE THREAD

**Issue by danaki** [blaze/blaze#1389]
Using ipython:

```
In [79]: from blaze import Data, compute

In [80]: df = Data('mongodb://localhost/db::cars', dshape='var * { production_year: int, price: real, url: string }')

In [81]: df.production_year.max()
Out[81]: 2015

In [82]: df.production_year.max() + 1
Out[82]:

In [83]: type(df.production_year.max() + 1)
Out[83]: blaze.expr.arithmetic.Add

In [84]: compute(df.production_year.max() + 1)
--------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-85-23e82ea579ff> in <module>()
----> 1 compute(df.production_year.max() + 1)

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/multipledispatch/dispatcher.pyc in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165
    166         except MDNotImplementedError:

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/interactive.pyc in compute(expr, **kwargs)
    169         raise ValueError("No data resources found")
    170     else:
--> 171         return compute(expr, resources, **kwargs)
    172
    173

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/multipledispatch/dispatcher.pyc in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165
    166         except MDNotImplementedError:

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/compute/core.pyc in compute(expr, d, **kwargs)
    402         d4 = d3
    403
--> 404     result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)
    405     if post_compute_:
    406         result = post_compute_(expr3, result, scope=d4)

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/compute/core.pyc in top_then_bottom_then_top_again_etc(expr, scope, **kwargs)
    195                                   "data: %s" % (expr3, scope4))
    196     else:
--> 197         return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)
    198
    199

/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/compute/core.pyc in top_then_bottom_then_top_again_etc(expr, scope, **kwargs)
    193         raise NotImplementedError("Don't know how to compute:\n"
    194                                   "expr: %s\n"
--> 195                                   "data: %s" % (expr3, scope4))
    196     else:
    197         return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

NotImplementedError: Don't know how to compute:
expr: production_year_max + 1
data: {production_year_max: <blaze.compute.mongo.MongoQuery object at 0x10d526650>}
```

Besides why (df.production_year.max() + 1) doesn't evaluate, but df.production_year.max() does? Isn't it unnatural behavior?

**Comment by kwmsmith** [comment]
Thanks for the bug report, we'll look into it.

Regarding why `df.production_year.max() + 1` doesn't evaluate: that's related to idiosyncrasies with how Blaze's implicit computation works with `repr`ing an interactive expression.  There are enough issues with this implicit computation that we will likely be deprecating and changing this to make it explicit in coming releases.  Surprises like empty evaluations won't happen anymore after these improvements.

**Comment by danaki** [comment]
Additionally sporadically I get this:
```
Traceback (most recent call last):
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yuri/work/ssguru/web/simple.py", line 156, in index
    plot = ChartPlot(ds)
  File "/Users/yuri/work/ssguru/web/simple.py", line 35, in __init__
    & (ds.production_year > (dt.date.today().year - 20))]
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/expr/core.py", line 207, in __lt__
    return self._lt(other)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/expr/expressions.py", line 215, in __getattr__
    schema_methods(self.dshape.measure),
  File "cytoolz/functoolz.pyx", line 369, in cytoolz.functoolz.c_memoize.__call__ (cytoolz/functoolz.c:5859)
    
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/weakref.py", line 372, in __contains__
    return wr in self.data
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/interactive.py", line 350, in <lambda>
    Expr.__nonzero__ = lambda x: convert_base(bool, x)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/interactive.py", line 339, in convert_base
    x = compute(x)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/interactive.py", line 171, in compute
    return compute(expr, resources, **kwargs)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/compute/core.py", line 404, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)
  File "/Users/yuri/anaconda2/envs/ssguru/lib/python2.7/site-packages/blaze/compute/core.py", line 195, in top_then_bottom_then_top_again_etc
    "data: %s" % (expr3, scope4))
NotImplementedError: Don't know how to compute:
expr: Broadcast(_children=(_3,), _scalars=(_3,), _scalar_expr=_3.mileage == _3.mileage)
data: {_3: <blaze.compute.mongo.MongoQuery object at 0x10d6dc7d0>}
```

The problem causing code looks like:
```
        self.ds = ds[(ds.mileage > 0)
            & (ds.mileage < 1e+6)
            & (ds.production_year > (dt.date.today().year - 20))]
``` 

This is Flask application so after I hit Refresh, the problem usually disappears. Can I help you more?
