### ISSUE TITLE
Method max on a database column returns an SQLAlchemy Select  object

### ISSUE THREAD

**Issue by dhirschfeld** [blaze/blaze#1403]
As discussed on gitter with an Oracle database, cx_oracle, Python 3.4 and blaze 0.9.0 I get the below behaviour:
```python
In [65]: temp.forecasttime
Out[65]:
         forecasttime
0   01-Apr-2010 07:00
1   01-Apr-2010 07:00
2   01-Apr-2010 07:00
3   01-Apr-2010 07:00
4   01-Apr-2010 07:00
5   01-Apr-2010 07:00
6   01-Apr-2010 07:00
7   01-Apr-2010 07:00
8   01-Apr-2010 07:00
9   01-Apr-2010 07:00
...

In [66]: temp.forecasttime.max()
Out[66]: <sqlalchemy.sql.selectable.Select at 0xf7e3198; Select object>
```

**Comment by dhirschfeld** [comment]
**Test Case:**
```python
from itertools import chain

from odo import odo
import pandas as pd
import sqlalchemy as sa


engine = sa.create_engine('sqlite://')
metadata = sa.MetaData(bind=engine)
table = sa.Table('demo', metadata,
   sa.Column('timestamp', sa.DateTime, primary_key=True),
)
metadata.create_all()

dates = pd.date_range('01-Feb-2016', '01-Mar-2016', freq='D')
odo(pd.DataFrame(dates, columns=['timestamp']), table)

assert dates.equals(pd.DatetimeIndex(chain(*table.select().execute().fetchall())))
```

**Comment by dhirschfeld** [comment]
On my home PC, with py35 against an in-memory sqlite db and blaze 0.8.3 it appears to work correctly
```python
In [42]: import blaze as bz

In [43]: bz.Data(table)
Out[43]:
    timestamp
0  2016-02-01
1  2016-02-02
2  2016-02-03
3  2016-02-04
4  2016-02-05
5  2016-02-06
6  2016-02-07
7  2016-02-08
8  2016-02-09
9  2016-02-10
...

In [44]: bz.Data(table).timestamp.max()
Out[44]: datetime.datetime(2016, 3, 1, 0, 0)

In [45]: bz.__version__
Out[45]: '0.8.3'
```

**Comment by dhirschfeld** [comment]
After updating my home PC to blaze 0.9.0 I get an error on repr but the data compares correctly:
```python
In [17]: bz.__version__
Out[17]: '0.9.0'

In [18]: bz.Data(table)
Out[18]: 
    timestamp
0  2016-02-01
1  2016-02-02
2  2016-02-03
3  2016-02-04
4  2016-02-05
5  2016-02-06
6  2016-02-07
7  2016-02-08
8  2016-02-09
9  2016-02-10
...

In [19]: bz.Data(table).timestamp.max()
Traceback (most recent call last):

  File "C:\bin\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 697, in __call__
    printer.pretty(obj)

  File "C:\bin\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)

  File "C:\bin\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)

  File "C:\bin\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 685, in _repr_pprint
    output = repr(obj)

  File "C:\bin\Anaconda3\lib\site-packages\blaze\interactive.py", line 263, in expr_repr
    return repr(coerce_scalar(compute(expr), str(expr.dshape)))

  File "C:\bin\Anaconda3\lib\site-packages\blaze\interactive.py", line 249, in coerce_scalar
    return coerce_(Timestamp)

  File "C:\bin\Anaconda3\lib\site-packages\blaze\interactive.py", line 235, in coerce_to
    return odo(x, typ, **(odo_kwargs or {}))

  File "C:\bin\Anaconda3\lib\site-packages\odo\odo.py", line 91, in odo
    return into(target, source, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\odo\into.py", line 43, in wrapped
    return f(*args, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\odo\into.py", line 53, in into_type
    return convert(a, b, dshape=dshape, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\odo\core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\odo\core.py", line 60, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)

  File "C:\bin\Anaconda3\lib\site-packages\odo\backends\dask.py", line 59, in array_to_dask
    raise ValueError("chunks cannot be None")

ValueError: chunks cannot be None


In [20]: print(bz.Data(table).timestamp.max())
max(_11.timestamp)

In [21]: bz.Data(table).timestamp.max() == dates[-1]
Out[21]: True
```

**Comment by dhirschfeld** [comment]
Trying to repro on my work PC it appears that it only happens when the data type is a string
```python
from itertools import chain

from numpy.random import choice
from odo import odo
import pandas as pd
import sqlalchemy as sa

engine = sa.create_engine('sqlite://')
metadata = sa.MetaData(bind=engine)
table = sa.Table('demo', metadata,
   sa.Column('timestamp', sa.String, primary_key=True),
)
metadata.create_all()

dates = pd.date_range('01-Feb-2016', '01-Mar-2016', freq='D')
df = pd.DataFrame({'timestamp': list(map(str, dates))})
odo(df, table)
```
```python
In [27]: bz.Data(table).timestamp.max()
Out[27]: <sqlalchemy.sql.selectable.Select at 0x1c77e021d30; Select object>
```

**Comment by llllllllll** [comment]
in your test on 0.9.0, the `chunks cannot be None` is due to a weight issue trying to route your conversion through dask. If you uninstall dask does it still happen? This bug looks like it is in `blaze.interactive.coerce_scalar`:

```python
def coerce_scalar(result, dshape, odo_kwargs=None):
    coerce_ = partial(coerce_to, x=result, odo_kwargs=odo_kwargs)
    if 'float' in dshape:
        return coerce_(float)
    if 'decimal' in dshape:
        return coerce_(decimal.Decimal)
    elif 'int' in dshape:
        return coerce_(int)
    elif 'bool' in dshape:
        return coerce_(bool)
    elif 'datetime' in dshape:
        return coerce_(Timestamp)
    elif 'date' in dshape:
        return coerce_(datetime.date)
    elif 'timedelta' in dshape:
        return coerce_(datetime.timedelta)
    else:
        return result
```

We are just repring anything that is not one of these types and there is no guard for `string`.

**Comment by dhirschfeld** [comment]
Note: To work around the chunks error I uninstalled dask temporarily after which the conversion appears to work but with the below error message:
```python
In [5]: max_forecastdatetime = odo(data.forecastdatetime.max(), pd.Timestamp)
~\Anaconda3\lib\site-packages\odo\core.py:65: FailedConversionWarning: Failed on float -> Timestamp. Working around
Error message:

  warn(FailedConversionWarning(A, B, e))

In [6]: max_forecastdatetime
Out[6]: Timestamp('2016-02-02 16:00:00')
```

**Comment by llllllllll** [comment]
This is a known warning for selectable->timestamp. I would just ignore it in the repl or in app code explicitly pass ignore_edges to get rid of it.
