### ISSUE TITLE
Cannot get tables after connecting to Oracle

### ISSUE THREAD

**Issue by junjiecai** [blaze/blaze#1429]
Hi, I meet a problem and I am not sure whether it's a bug.

I connected the Oracle Database using

```
d = Data('oracle://<username>:<password>@<databaseIP>/<SID>')
```
I got a blaze data object but it contains no table

But I tried the same connection in same machine with cx_oracle and it can successfully access the target table. 

So what's wrong here?

Thanks.

**Comment by kwmsmith** [comment]
Hi @junjiecai,

Can you explore the `d` object you get back from the `Data` call?  What attributes does it have?  Since you don't specify a table in the URI, you'll have to use dot  notation to access any underlying tables.

> But I tried the same connection in same machine with cx_oracle and it can successfully access the target table. 

To be clear, the working cx_oracle example goes through `Data`?

Another way to troubleshoot is to see if you can connect to the DB via a [SQLA engine](http://docs.sqlalchemy.org/en/latest/core/engines.html#oracle) directly, since that's what Blaze and Odo are doing under the hood.

**Comment by dhirschfeld** [comment]
FWIW with blaze I can't directly connect to a table in an oracle database:
```python
In [27]: bz.Data("oracle+cx_oracle://{}:{}@{}::{}".format(user, password, db, table_name))
ValueError: Table does not exist and no dshape provided

In [28]: bz.Data("oracle+cx_oracle://{}:{}@{}::{}.{}".format(user, password, db, schema, table_name))
ValueError: Table does not exist and no dshape provided
```
...however I can connect to it with SQLA and then simply wrap it with `bz.Data`:
```python
In [29]: engine = sa.create_engine("oracle+cx_oracle://{}:{}@{}".format(user, password, db))
    ...: metadata = sa.MetaData(bind=engine)
    ...: table = sa.Table(table_name, metadata, autoload=True, schema=schema)

In [30]: data = bz.Data(table)

In [31]: 
```

**Comment by junjiecai** [comment]
Hi @kwmsmith,

I tried
```
d = Data('oracle://<username>:<password>@<databaseIP>/<SID>::<SCHEMA>.<TABLE>')
```
Then blaze tells me the table doesn't exist.

And I tried 
```
d.data.table_names()
```
Then I got an empty list.


However, these pure cx_oracle codes below work well
```
conn = cx_Oracle.connect('pm/aaa111@192.168.1.203/eskbak1')
cusor = conn.cursor()
cursor.execute('select * from <SCHEMA>.<TABLE>')
rows = cursor.fetchall()
...


P.S. I tried connecting several different Oracle databases through BLAZE. It doesn't always fail, but only pure cx_Oracle code can guarantee the connection.

**Comment by kwmsmith** [comment]
> FWIW with blaze I can't directly connect to a table in an oracle database:

```
In [27]: bz.Data("oracle+cx_oracle://{}:{}@{}::{}".format(user, password, db, table_name))
ValueError: Table does not exist and no dshape provided
```

@dhirschfeld can you cut and paste the full traceback?  That will help me trace the code path.  We don't have an oracle deployment, so I'll need you and @junjiecai to help here.

**Comment by dhirschfeld** [comment]
Full traceback is:
```python-traceback
In [12]: bz.Data("oracle+cx_oracle://{}:{}@{}::{}.{}".format(user, password, db, schema, table_name))
Traceback (most recent call last):

  File "<ipython-input-12-b4b8580848b2>", line 1, in <module>
    bz.Data("oracle+cx_oracle://{}:{}@{}::{}.{}".format(user, password, db, schema, table_name))

  File "~\Anaconda3\lib\site-packages\blaze\interactive.py", line 110, in Data
    data = resource(data, schema=schema, dshape=dshape, **kwargs)

  File "~\Anaconda3\lib\site-packages\odo\regex.py", line 91, in __call__
    return self.dispatch(s)(s, *args, **kwargs)

  File "~\Anaconda3\lib\site-packages\odo\resource.py", line 106, in resource_split
    return resource(uri, other, *args, **kwargs)

  File "~\Anaconda3\lib\site-packages\odo\regex.py", line 91, in __call__
    return self.dispatch(s)(s, *args, **kwargs)

  File "~\Anaconda3\lib\site-packages\odo\backends\sql.py", line 560, in resource_sql
    raise ValueError("Table does not exist and no dshape provided")

ValueError: Table does not exist and no dshape provided
```
Some context:
```python-traceback
In [13]: debug
> ~\anaconda3\lib\site-packages\odo\backends\sql.py(560)resource_sql()
    558             return t
    559         else:
--> 560             raise ValueError("Table does not exist and no dshape provided")
    561 
    562     # We were not given a table name


ipdb> u
> ~\anaconda3\lib\site-packages\odo\regex.py(91)__call__()
     89 
     90     def __call__(self, s, *args, **kwargs):
---> 91         return self.dispatch(s)(s, *args, **kwargs)
     92 
     93     @property


ipdb> args
self = <odo.regex.RegexDispatcher object at 0x000000000B139BA8>
s = 'oracle+cx_oracle://<USER>:<PASSWORD>@<DB>'
args = ('<SCHEMA>.<TABLE>',)
kwargs = {'dshape': None, 'schema': None}
```
...so it seems that the schema isn't being picked up correctly, however I'm not sure how to correctly specify a schema for a `bz.Data` object?

**Comment by dhirschfeld** [comment]
So, it looks like its' expecting schema as a kwarg so I tried that with some success:
```python-traceback
In [23]: data = bz.Data("oracle+cx_oracle://{}:{}@{}::{}".format(user, password, db, table_name), schema=schema)

In [24]: data
Traceback (most recent call last):

  File "~\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 699, in __call__
    printer.pretty(obj)

  File "~\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)

  File "~\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)

  File "~\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 694, in _repr_pprint
    output = repr(obj)

  File "~\Anaconda3\lib\site-packages\blaze\interactive.py", line 268, in expr_repr
    return repr_tables(expr, 10)

  File "~\Anaconda3\lib\site-packages\blaze\interactive.py", line 201, in repr_tables
    result = concrete_head(expr, n).rename(columns={None: ''})

  File "~\Anaconda3\lib\site-packages\blaze\interactive.py", line 186, in concrete_head
    df.columns = [expr._name]

  File "~\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2371, in __setattr__
    return object.__setattr__(self, name, value)

  File "pandas\src\properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas\lib.c:45002)

  File "~\Anaconda3\lib\site-packages\pandas\core\generic.py", line 425, in _set_axis
    self._data.set_axis(axis, labels)

  File "~\Anaconda3\lib\site-packages\pandas\core\internals.py", line 2572, in set_axis
    'new values have %d elements' % (old_len, new_len))

ValueError: Length mismatch: Expected axis has 31 elements, new values have 1 elements
```
However the resulting data object can't be repr'd.

Which may be because the dshape isn't being correctly picked up:
```python
In [25]: data.dshape
Out[25]: dshape("var * <SCHEMA>")
```

But odo can still push it into a DataFrame despite the incorrectly specified datashape:
```python
In [27]: df = odo(data.head(), pd.DataFrame)

In [28]: df.shape
Out[28]: (10, 31)

In [29]: df.dtypes
Out[29]: 
forecasttime                   object
datetime               datetime64[ns]
location                       object
temperature                    object
dewpoint                       object
relativehumidity               object
windspeed                      object
lastchanged            datetime64[ns]
winddirection                  object
apparenttemperature            object
                            ...      
<snip>
```

**Comment by rsdenijs** [comment]
Is there any update on this? Im having the same problem. Although im not even able to use odo to pull data.

**Comment by rsdenijs** [comment]
Particularly one thing I tried was

```
data = blaze.Data(connection_string, table='<SCHEMA>.<TABLE>')
odo.odo(data,',myfile.csv')

```
I can use the connection string to do queries using sqlalchemy.

However, this produces (also shifting the schema to its own kwarg)

```

> ~/.virtualenvs/cross/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.pyc in single_source_dijkstra(G, source, target, cutoff, weight)
>     294     paths = {source: [source]}  # dictionary of paths
>     295     return _dijkstra(G, source, get_weight, paths=paths, cutoff=cutoff,
> --> 296                      target=target)
>     297 
>     298 
> 
> 
> ~/.virtualenvs/cross/local/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/weighted.pyc in _dijkstra(G, source, get_weight, pred, paths, cutoff, target)
>     354             break
>     355 
> --> 356         for u, e in G_succ[v].items():
>     357             cost = get_weight(v, u, e)
>     358             if cost is None:
> 
> KeyError: <class 'sqlalchemy.engine.base.Engine'>

```

**Comment by dhirschfeld** [comment]
Does my workaround above of wrapping the SQLA table object not work for you?

**Comment by rsdenijs** [comment]
You mean specifying the table in the connection string and the schema in the kwargs?

my connection string has the format
'oracle+cx_oracle://<user>:<pass>@<server>:<port>/?service_name=<somename>'
I tried putting '::<tablename>' at many places but it does not work and specifying a tablename in the connection string does not even seem to be documented 
http://docs.sqlalchemy.org/en/latest/dialects/oracle.html#module-sqlalchemy.dialects.oracle.cx_oracle

Any ideas?

**Comment by dhirschfeld** [comment]
No, as above:
```
In [29]: engine = sa.create_engine("oracle+cx_oracle://{}:{}@{}".format(user, password, db))
    ...: metadata = sa.MetaData(bind=engine)
    ...: table = sa.Table(table_name, metadata, autoload=True, schema=schema)

In [30]: data = bz.Data(table)

In [31]: 
```

**Comment by rsdenijs** [comment]
In that case I get a horrible RuntimeError (Because of maximum recursion depth).
odo/backends/sql.py and multipledispatch/dispatcher.py seem to be playing ping-pong. 

```
   188 def discover_foreign_key_relationship(fk, parent, parent_measure=None):
    189     if fk.column.table is not parent:
--> 190         parent_measure = discover(fk.column.table).measure
```
```

   188 def discover_foreign_key_relationship(fk, parent, parent_measure=None):
    189     if fk.column.table is not parent:
--> 190         parent_measure = discover(fk.column.table).measure
```

**Comment by kwmsmith** [comment]
Apologies for the low bandwidth here.

For the record, the sqlalchemy magical incantation is:

    oracle+cx_oracle://user:pass@host:port/dbname[?key=value&key=value...]

It looks like you are aware of this.

Try passing the table name as an additional *positional* argument after the URI string, with an explicit `schema` kwarg:

```python
bz.Data("oracle+cx_oracle://user:pass@host:port/dbname", "tablename", schema="{...}")
```

The `schema` should look like `{col1: type1, col2: type2, ...}`.

@dhirschfeld what does your `schema` argument look like?

**Comment by rsdenijs** [comment]
I was missunderstanding the schema kwarg. I was giving it the schema _name_
I feel that the source of my problem is that I dont know how im supposed to specify the fully qualified name of the table. 
It is not possible to specify the schema name in the connection uri and I dont know where else to put it.

**Comment by kwmsmith** [comment]
> I feel that the source of my problem is that I dont know how im supposed to specify the fully qualified name of the table. 

For a non-oracle person, can you provide links or background material on how Oracle handles "fully qualified" table names, and schemas?  I have the sense we're using the same words with different meanings; although I could be very well be wrong here.

The escape hatch for various sql dialects in blaze has always been to create the sqla engine directly, create a table from that, and then wrap that in `blaze.Data`, as @dhirschfeld indicates above.

If blaze / odo are having trouble with your table due to foreign keys, etc, then I'll need to know the datashape of the tables in question.

As you and @dhirschfeld are discovering, Blaze hasn't been tested thoroughly against the many SQL dialects out there -- the primary dialect / implementation is PostgreSQL, and to a lesser extent, sqlite and mysql.  With other implementations (particularly proprietary ones like Oracle) the experience is significantly hampered by lack of testing, and minimal resources to support all SQL flavors out there.  

So your help and input here is very much appreciated.

**Comment by dhirschfeld** [comment]
@rsdenijs - if you can connect to the table but odo fails that seems like a separate issue. It's impossible to tell without you posting the *exact* code you used and the *exact* error message including the *full* traceback you got. If it's huge just post it in a gist.

**Comment by dhirschfeld** [comment]
@kwmsmith - it seems the usage of schema in that context is different from it's meaning as applied to databases (except sqlite because it doesn't have that concept AFAIK)

All enterprise DBs I know (postgres/sqlserver/oracle) have the concept of a schema as a *"namespace"* for containing tables. i.e. the database is a container of schemas which themselves are the objects which hold the actual tables. The fully qualified name of a table is therefore `[Database].[Schema].[Table]`

This fact is often overlooked there is a default schema (dbo/public in SQLServer/postgres) which is where any tables will go if no schema is specified. As shown in my example the schema needs to be passed to the SQLA table constructor so that it knows where to find the table in the database. This is only not true when the table is located in the default schema and hence `schema='dbo'` is passed implicitly for mssql or `schema='public'` for postgres

In my particular case the fully qualified name of the table is `[TradingAnalytics].[PRICES].[ContractPrices]` so the SQLA table object is constructed as:
```
engine = sa.create_engine("oracle+cx_oracle://{}:{}@TradingAnalytics".format(user, password))
metadata = sa.MetaData(bind=engine)
table = sa.Table('ContractPrices', metadata, autoload=True, schema='PRICES')
```

It appears that the usage above looks more like a datashape definition for a table? If schema has been overloaded to mean something different to it's usage in SQLA there still needs to be a way to pass it to the SQLA layer - maybe `database_schema`? 


http://blog.sqlauthority.com/2009/09/07/sql-server-importance-of-database-schemas-in-sql-server/
http://www.postgresql.org/docs/8.1/static/ddl-schemas.html

**Comment by dhirschfeld** [comment]
I'm actually a bit confused what the `schema` argument to `bz.Data` is? From your description above it looks like a `{column_name: data_type}` mapping which seems to me to be the same as a `dshape`?

The `bz.Data` docstring isn't much help as it seems to be omitted entirely from there! Also, if name is supposed to be used to specify the table name in the database something to that effect should probably be mentioned in the docstring as:
> A name for the data

...suggests to me a simple label rather than any association with the table name.
```python
In [8]: bz.Data?
Signature: bz.Data(data, dshape=None, name=None, fields=None, schema=None, **kwargs)
Docstring:
Interactive data.

The ``Data`` object presents a familiar view onto a variety of forms of
data.  This user-level object provides an interactive experience to using
Blaze's abstract expressions.

Parameters
----------
data : object
    Any type with ``discover`` and ``compute`` implementations
fields : list, optional
    Field or column names, will be inferred from datasource if possible
dshape : str or DataShape, optional
    DataShape describing input data
name : str, optional
    A name for the data.

Examples
--------
>>> t = Data([(1, 'Alice', 100),
...           (2, 'Bob', -200),
...           (3, 'Charlie', 300),
...           (4, 'Denis', 400),
...           (5, 'Edith', -500)],
...          fields=['id', 'name', 'balance'])
>>> t[t.balance < 0].name
    name
0    Bob
1  Edith
```

**Comment by dhirschfeld** [comment]
NB: Since I'm not offering to do the work and since there's a simple workaround of constructing the table in SQLA first I'm not actually asking for (or even suggesting) anything be done* - there are probably more important things to work on


\* with the exception perhaps of better documentation of the `schema` argument

**Comment by rsdenijs** [comment]
The problem is that the workaround is not working either

I create a table object

`table = sqlalchemy.Table('<tablename>', metadata, autoload=True, schema='<schemaname>')
`

And I can select a row
`table.select().execute().fetchone()`

I try to apply the workaround
`blaze.Data(table)
`

And then we enter a seemingly endless recursion.

https://gist.github.com/rsdenijs/0d92b5225155f87255359c234cdc0c4c

My knowledge of Blaze is very limited but since Sqlalchemy and Pandas work it seems to be a Blaze issue?

**Comment by rsdenijs** [comment]
I dont know if this counts as 'datashape' but here are the types of the columns that appear in the table as reported by sqlalchemy
https://gist.github.com/rsdenijs/41c5cf3c781804a3cbd2cc5a976d30bd

**Comment by dhirschfeld** [comment]
@rsdenijs - it seems that is a separate issue from blaze not supporting database schemas so it may be a new issue for it.

You may have to specify the exact database schema in the issue though as it looks like the issue is actually in odo being unable to handle the specific constraints.
