### ISSUE TITLE
blaze.merge with SQL Server

### ISSUE THREAD

**Issue by thequackdaddy** [blaze/blaze#1438]
Hello,

I'm working with Blaze and Microsoft SQL Server. 

When I try to do `bz.merge`, I get some problems...

````
data = bz.Data(odo.resource('mssql+pyodbc://SQLServer::Table',schema='dbo'))
bz.merge(data.field1, data.field2)

Traceback (most recent call last):

  File "C:\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 343, in __call__
    return method()

  File "C:\Anaconda3\lib\site-packages\blaze\interactive.py", line 326, in <lambda>
    Expr._repr_html_ = lambda x: to_html(x)

  File "C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\interactive.py", line 298, in to_html
    return to_html(concrete_head(expr))

  File "C:\Anaconda3\lib\site-packages\blaze\interactive.py", line 186, in concrete_head
    return odo(head, DataFrame)

  File "C:\Anaconda3\lib\site-packages\odo-0.4.2+3.g65b44d4-py3.5.egg\odo\odo.py", line 91, in odo
    return into(target, source, **kwargs)

  File "C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\interactive.py", line 313, in into
    result = compute(b, **kwargs)

  File "C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\interactive.py", line 171, in compute
    return compute(expr, resources, **kwargs)

  File "C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 404, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 197, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 167, in top_then_bottom_then_top_again_etc
    expr2, scope2 = bottom_up_until_type_break(expr, scope, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 309, in bottom_up_until_type_break
    for i in inputs])

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 309, in <listcomp>
    for i in inputs])

  File "C:\Anaconda3\lib\site-packages\blaze\compute\core.py", line 332, in bottom_up_until_type_break
    **kwargs)}

  File "C:\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\blaze\compute\sql.py", line 974, in compute_up
    assert len(from_obj) == 1, 'only a single FROM clause supported'

AssertionError: only a single FROM clause supported
```
it appears that blaze is doing...

    select field1 from data 
    select field2 from data

when it should be doing...

    select field1, field2 from data

Anyone know how to fix? I appreciate this is probably SQLAlchemy related, but I'm oblivious to the inner workings.

**Comment by thequackdaddy** [comment]
I realized that I think blaze.transform is what I'm trying to do.
