### ISSUE TITLE
isin not working correctly on a filtered table?

### ISSUE THREAD

**Issue by dhirschfeld** [blaze/blaze#1485]
I'm on Windows, connecting to an Oracle DB with cxOracle. When trying to filter on a specific set of ids blaze isn't returning the rows even though they exist in the DB. It may be important that calling `bz.compute` on the result throws a `NotImplementedError`

```python
In [129]: data
Out[129]: 
   cc_id    cc_reference
0  27410  FUTA6437S-Q316
1  27411  FUTA6437S-Q416
2  27412  FUTA6437S-Q117
3  27413  FUTA6437S-Q217
4  27414  FUTA7202S-Q118
5  27415       FUTA7203S
6  27428  FUTA7205S-Q218
7  27429  FUTA7205S-Q318
8  27430  FUTA7205S-Q418
9  27435       FUTA7207B

In [130]: data[data.cc_id == 27410]
Out[130]: 
   cc_id    cc_reference
0  27410  FUTA6437S-Q316

In [131]: data[data.cc_id.isin({27410})]

In [132]: type(data[data.cc_id.isin({27410})])
Out[132]: blaze.expr.expressions.Selection

In [133]: bz.compute(data[data.cc_id.isin({27410})])
Traceback (most recent call last):

  File "<ipython-input-133-8b20a8ca4c59>", line 1, in <module>
    bz.compute(data[data.cc_id.isin({27410})])

  File "C:\Python\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Python\lib\site-packages\blaze\interactive.py", line 168, in compute
    return compute(expr, resources, **kwargs)

  File "C:\Python\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 406, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 198, in top_then_bottom_then_top_again_etc
    return top_then_bottom_then_top_again_etc(expr3, scope4, **kwargs)

  File "C:\Python\lib\site-packages\blaze\compute\core.py", line 196, in top_then_bottom_then_top_again_etc
    "data: %s" % (expr3, scope4))

NotImplementedError: Don't know how to compute:
expr: _[cc_id.isin(frozenset({27410}))]
data: {_: <sqlalchemy.sql.selectable.Select at 0xe8fdac8; Select object>, cc_id: <sqlalchemy.sql.selectable.Select at 0x1369c860; Select object>}

```

**Comment by dhirschfeld** [comment]
**Repro:**
```python
import blaze as bz
from numpy.random import randn
import sqlalchemy as sa

engine = sa.create_engine('sqlite://')
metadata = sa.MetaData(bind=engine)

table = sa.Table(
    'Test', metadata,
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('value', sa.Float(32), nullable=False),
)

records = [
    {'id': idx, 'value': value}
    for idx, value
    in enumerate(randn(10))
]

with engine.connect() as conn:
    conn.execute(table.insert(), records)
    
    
data = bz.Data(table)
data = data[data.id > 4]
assert data[data.id.isin({5,7,9})].nrows == 3
```
```
NotImplementedError: Don't know how to compute:
expr: (nelements(_2[id.isin(frozenset({9, 5, 7}))])) == 3
data: {_2: <sqlalchemy.sql.selectable.Select at 0xe990668; Select object>, id: <sqlalchemy.sql.selectable.Select at 0xe990978; Select object>}
```

**Comment by a-campbell** [comment]
I am also running into this error with a Postgres backend and an `isin` query for an array of strings. It doesn't seem to matter whether the data is filtered or not. 

Downgrading from 0.10.1 to 0.8.3 solved the problem.

**Comment by llllllllll** [comment]
I bet we have a dispatch on `Select` instead of `Selectable`
