### ISSUE TITLE
Strange things happen when mixing different instances of a bz.Data object

### ISSUE THREAD

**Issue by dhirschfeld** [blaze/blaze#1557]
In my larger example I get incorrect SQL issued and an SQL error. In my repro below it throws a ValueError.

It may be the case that the answer is simply *"Don't Do That"* but in that case it may still be nice if it's possible to detect it to then throw a more meaningful error.

**Comment by dhirschfeld** [comment]
Using the same test case as in https://github.com/blaze/blaze/issues/1552#issuecomment-235126768 I observe the following behaviour:
```python
In [8]: def get_data():
   ...:     """Returns a *new* `bz.Data` object wrapping the same table"""
   ...:     return bz.Data(T1)

In [9]: mask = get_data().label_id.isin({2})

In [10]: odo(get_data()[mask], pd.DataFrame)
Traceback (most recent call last):

  File "<ipython-input-10-340392c503d0>", line 1, in <module>
    odo(get_data()[mask], pd.DataFrame)

  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 132, in __getitem__
    return selection(self, key)

  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 523, in selection
    subexpr = common_subexpression(table, predicate)

  File "c:\dev\packages\blaze\blaze\expr\core.py", line 502, in common_subexpression
    'No common leaves found in expressions %s' % list(exprs)

ValueError: No common leaves found in expressions [<'Table' data; _name='_3', dshape='var * {  timestamp: string,  label_id: map[int32, ...'>,    label_id
0     False
1     False
2      True
3      True
4     False
5      True
6     False
7     False
8      True
9     False
...]
```

**Comment by dhirschfeld** [comment]
In my larger example I get an even more opaque DatabaseError but I haven't been able to isolate a test case to repro it exactly.

As you can see below though it looks like its raising an exception in the same `common_subexpression` but somehow that's being caught and actual incorrect SQL is issued to the DB
```
  File "c:\dev\packages\blaze\blaze\expr\core.py", line 502, in common_subexpression
    'No common leaves found in expressions %s' % list(exprs)
```

```python
In [5]: mask = schema.HOLIDAY_SCHEDULE.hs_hc_id.isin({1})

In [6]: schema.HOLIDAY_SCHEDULE[mask]
Traceback (most recent call last):

  File "<ipython-input-6-5927c2648912>", line 1, in <module>
    schema.HOLIDAY_SCHEDULE[mask]

  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 132, in __getitem__
    return selection(self, key)

  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 523, in selection
    subexpr = common_subexpression(table, predicate)

  File "c:\dev\packages\blaze\blaze\expr\core.py", line 502, in common_subexpression
    'No common leaves found in expressions %s' % list(exprs)

  File "c:\dev\packages\blaze\blaze\interactive.py", line 444, in _choose_repr
    return expr_repr(self)

  File "c:\dev\packages\blaze\blaze\interactive.py", line 360, in expr_repr
    return repr_tables(expr, 10)

  File "c:\dev\packages\blaze\blaze\interactive.py", line 242, in repr_tables
    result = concrete_head(expr, n).rename(columns={None: ''})

  File "c:\dev\packages\blaze\blaze\interactive.py", line 232, in concrete_head
    df = odo(head, DataFrame)

  File "c:\dev\packages\odo\odo\odo.py", line 91, in odo
    return into(target, source, **kwargs)

  File "C:\Python\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "c:\dev\packages\blaze\blaze\interactive.py", line 406, in into
    return into(a, result, **kwargs)

  File "C:\Python\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)

  File "c:\dev\packages\odo\odo\into.py", line 43, in wrapped
    return f(*args, **kwargs)

  File "c:\dev\packages\odo\odo\into.py", line 53, in into_type
    return convert(a, b, dshape=dshape, **kwargs)

  File "c:\dev\packages\odo\odo\core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)

  File "c:\dev\packages\odo\odo\core.py", line 60, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)

  File "c:\dev\packages\odo\odo\backends\sql.py", line 652, in select_or_selectable_to_frame
    columns, rows = batch(el, bind=bind)

  File "c:\dev\packages\odo\odo\backends\sql.py", line 144, in batch
    return next(terator), concat(terator)

  File "c:\dev\packages\odo\odo\backends\sql.py", line 134, in rowterator
    result = conn.execute(sel)

  File "C:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "C:\Python\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "C:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "C:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)

  File "C:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "C:\Python\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "C:\Python\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)

  File "C:\Python\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)

  File "C:\Python\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

DatabaseError: (cx_Oracle.DatabaseError) ORA-00923: FROM keyword not found where expected
 [SQL: '''
    SELECT anon_1
    FROM (
        SELECT "CALENDARS"."HOLIDAY_SCHEDULE".hs_hc_id IN (:hs_hc_id_1) AS anon_1
        FROM "CALENDARS"."HOLIDAY_SCHEDULE"
    )
    WHERE ROWNUM <= :param_1
'''] [parameters: {'param_1': 11, 'hs_hc_id_1': 1}]
```

**Comment by dhirschfeld** [comment]
...so, the reason why my oracle case fails in a different manner is that the [below](https://github.com/blaze/blaze/blob/4a3afbec552728c5d1484ae90e2b5fd918ed0c28/blaze/expr/core.py#L502) code fails when trying to repr the `exprs`
```python
    # no common leaves therefore no common subexpression
    if not leaves:
        raise ValueError(
            'No common leaves found in expressions %s' % list(exprs)
        )
```
I'm not sure how repr is being called but the below code seems to fix the problem with the incorrect exception being thrown:
```python
    # no common leaves therefore no common subexpression
    if not leaves:
        raise ValueError(
            'No common leaves found in expressions %s' % list(map(str, exprs))
        )
```
...after which I then get the same *no common leaves* exception
```python
  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 132, in __getitem__
    return selection(self, key)
  File "c:\dev\packages\blaze\blaze\expr\expressions.py", line 523, in selection
    subexpr = common_subexpression(table, predicate)
  File "c:\dev\packages\blaze\blaze\expr\core.py", line 502, in common_subexpression
    'No common leaves found in expressions %s' % list(map(str, exprs))
ValueError: No common leaves found in expressions ['_2', '_1.hs_hc_id.isin(frozenset({1}))']
```

**Comment by kwmsmith** [comment]
Thanks for writing up the issue.  This exposes a current design flaw; Blaze currently assumes that different `Data` objects refer to different datasets; the internal logic for selecting based on your `mask` tries to enforce that the table used for the predicate is the same as the table being selected.

Some questions and comments:
* what version of Blaze are you using here?
* Please try this example against the most recent Blaze release and let us know if it still errors.
* You will need to change the `bz.Data()` to `bz.data()` in the most recent version of Blaze -- that is the user-facing API for creating `Data` objects.  There is logic in `bz.data()` and I'm curious if it resolves this issue for us already.

If the issue is still there with recent Blaze, then one possible solution would be to leverage the current expression cache and make `Data` objects singletons based on the underlying dataset, in the same way that other blaze expressions are also singletons based on their arguments, that way the get_data()[mask] expression would only refer to a single `Data` source.

**Comment by dhirschfeld** [comment]
I'm running from a source checkout of the latest master `bz.Data` still seems to be around and doesn't issue a deprecation warning AFAICS. The behaviour is the same regardless of which (data/Data) I use.

I guess it would be nice for it to work but as mentioned I'm happy enough for it to be unsupported though a better error message would be helpful if possible. My major issue was that a completely unrelated error was being thrown when trying to repr the expression which totally threw me off track for a bit. At least `no common leaves found` is suggestive of the underlying cause of the problem.

**Comment by kwmsmith** [comment]
> I'm running from a source checkout of the latest master bz.Data still seems to be around and doesn't issue a deprecation warning AFAICS. The behaviour is the same regardless of which (data/Data) I use.

Hmm, OK, thanks for checking.  It doesn't matter here, but `data()` is meant to be the public API -- in the future `data()` may have logic in it that `Data` doesn't.

> I guess it would be nice for it to work but as mentioned I'm happy enough for it to be unsupported though a better error message would be helpful if possible.

OK, thanks for the input -- agreed on better error messages.
