### ISSUE TITLE
NotImplementedError: No SQL-datashape match for type JSONB

### ISSUE THREAD

**Issue by analyticalmonk** [blaze/blaze#1633]
When I try to connect to certain type of tables* in my postgres DB using blaze, I get the error described in the heading.
It goes something like this:
```
db_uri = ("postgresql://<relevant_string>/production::table1")
db = blaze.data(db_uri)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/blaze/interactive.py", line 143, in data
    return _Data(data_source, discover(data_source), name)
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/odo/backends/sql.py", line 203, in discover_sqlalchemy_selectable
    record = list(_process_columns(t.columns))
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/odo/backends/sql.py", line 225, in _process_columns
    (name, dtype), = discover(col).fields
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/odo/backends/sql.py", line 197, in discover_sqlalchemy_column
    return Record([(c.name, meta(discover(c.type)))])
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/home/redcarpet/miniconda2/envs/desktop_ux/lib/python3.6/site-packages/odo/backends/sql.py", line 184, in discover_typeengine
    raise NotImplementedError("No SQL-datashape match for type %s" % typ)
NotImplementedError: No SQL-datashape match for type JSONB

```

*Types of tables which throw an error:
- Contain a JSONB column.
- Are referenced by or reference a table containing a JSONB column.

**Comment by ljluestc** [comment]
from sqlalchemy import create_engine
import blaze as bz

# Replace with your actual database URL
db_uri = "postgresql://<relevant_string>/production"

# Create a SQLAlchemy engine
engine = create_engine(db_uri)

# Fetch the data using SQLAlchemy and convert to Blaze DataFrame
def fetch_jsonb_table(table_name):
    query = f"SELECT * FROM {table_name}"
    result = engine.execute(query)
    data = result.fetchall()
    column_names = result.keys()
    return bz.DataFrame(data, columns=column_names)

# Replace "table1" with the actual table name containing JSONB column
blaze_df = fetch_jsonb_table("table1")

print(blaze_df)
